// Code generated by MockGen. DO NOT EDIT.
// Source: internal/auth/repository.go

// Package auth is a generated GoMock package.
package auth

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockAuthAttemptRepository is a mock of AuthAttemptRepository interface.
type MockAuthAttemptRepository struct {
	ctrl     *gomock.Controller
	recorder *MockAuthAttemptRepositoryMockRecorder
}

// MockAuthAttemptRepositoryMockRecorder is the mock recorder for MockAuthAttemptRepository.
type MockAuthAttemptRepositoryMockRecorder struct {
	mock *MockAuthAttemptRepository
}

// NewMockAuthAttemptRepository creates a new mock instance.
func NewMockAuthAttemptRepository(ctrl *gomock.Controller) *MockAuthAttemptRepository {
	mock := &MockAuthAttemptRepository{ctrl: ctrl}
	mock.recorder = &MockAuthAttemptRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuthAttemptRepository) EXPECT() *MockAuthAttemptRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAuthAttemptRepository) Create(ctx context.Context, attempt AuthAttempt) (*AuthAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, attempt)
	ret0, _ := ret[0].(*AuthAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockAuthAttemptRepositoryMockRecorder) Create(ctx, attempt interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAuthAttemptRepository)(nil).Create), ctx, attempt)
}

// Delete mocks base method.
func (m *MockAuthAttemptRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockAuthAttemptRepositoryMockRecorder) Delete(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockAuthAttemptRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockAuthAttemptRepository) GetByID(ctx context.Context, id string) (*AuthAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*AuthAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockAuthAttemptRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockAuthAttemptRepository)(nil).GetByID), ctx, id)
}

// GetByTelegramUsername mocks base method.
func (m *MockAuthAttemptRepository) GetByTelegramUsername(ctx context.Context, username string) (*AuthAttempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTelegramUsername", ctx, username)
	ret0, _ := ret[0].(*AuthAttempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTelegramUsername indicates an expected call of GetByTelegramUsername.
func (mr *MockAuthAttemptRepositoryMockRecorder) GetByTelegramUsername(ctx, username interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTelegramUsername", reflect.TypeOf((*MockAuthAttemptRepository)(nil).GetByTelegramUsername), ctx, username)
}

// Update mocks base method.
func (m *MockAuthAttemptRepository) Update(ctx context.Context, id string, dto UpdateAuthAttemptDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockAuthAttemptRepositoryMockRecorder) Update(ctx, id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockAuthAttemptRepository)(nil).Update), ctx, id, dto)
}
