// Code generated by MockGen. DO NOT EDIT.
// Source: internal/articles/repository.go

// Package articles is a generated GoMock package.
package articles

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockArticleRepository is a mock of ArticleRepository interface.
type MockArticleRepository struct {
	ctrl     *gomock.Controller
	recorder *MockArticleRepositoryMockRecorder
}

// MockArticleRepositoryMockRecorder is the mock recorder for MockArticleRepository.
type MockArticleRepositoryMockRecorder struct {
	mock *MockArticleRepository
}

// NewMockArticleRepository creates a new mock instance.
func NewMockArticleRepository(ctrl *gomock.Controller) *MockArticleRepository {
	mock := &MockArticleRepository{ctrl: ctrl}
	mock.recorder = &MockArticleRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockArticleRepository) EXPECT() *MockArticleRepositoryMockRecorder {
	return m.recorder
}

// CloneWithIncrementedVersion mocks base method.
func (m *MockArticleRepository) CloneWithIncrementedVersion(ctx context.Context, id string) (*ReadArticleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CloneWithIncrementedVersion", ctx, id)
	ret0, _ := ret[0].(*ReadArticleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CloneWithIncrementedVersion indicates an expected call of CloneWithIncrementedVersion.
func (mr *MockArticleRepositoryMockRecorder) CloneWithIncrementedVersion(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CloneWithIncrementedVersion", reflect.TypeOf((*MockArticleRepository)(nil).CloneWithIncrementedVersion), ctx, id)
}

// Create mocks base method.
func (m *MockArticleRepository) Create(ctx context.Context, dto CreateArticleDTO) (*ReadArticleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, dto)
	ret0, _ := ret[0].(*ReadArticleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockArticleRepositoryMockRecorder) Create(ctx, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockArticleRepository)(nil).Create), ctx, dto)
}

// DeleteByID mocks base method.
func (m *MockArticleRepository) DeleteByID(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockArticleRepositoryMockRecorder) DeleteByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockArticleRepository)(nil).DeleteByID), ctx, id)
}

// Find mocks base method.
func (m *MockArticleRepository) Find(ctx context.Context, filter FilterArticlesDTO) ([]*ReadArticleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, filter)
	ret0, _ := ret[0].([]*ReadArticleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockArticleRepositoryMockRecorder) Find(ctx, filter interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockArticleRepository)(nil).Find), ctx, filter)
}

// FindAllVersions mocks base method.
func (m *MockArticleRepository) FindAllVersions(ctx context.Context, courseID, title string) ([]*ReadArticleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllVersions", ctx, courseID, title)
	ret0, _ := ret[0].([]*ReadArticleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllVersions indicates an expected call of FindAllVersions.
func (mr *MockArticleRepositoryMockRecorder) FindAllVersions(ctx, courseID, title interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllVersions", reflect.TypeOf((*MockArticleRepository)(nil).FindAllVersions), ctx, courseID, title)
}

// GetByID mocks base method.
func (m *MockArticleRepository) GetByID(ctx context.Context, id string) (*ReadArticleDTO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*ReadArticleDTO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockArticleRepositoryMockRecorder) GetByID(ctx, id interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockArticleRepository)(nil).GetByID), ctx, id)
}

// UpdateByID mocks base method.
func (m *MockArticleRepository) UpdateByID(ctx context.Context, id string, dto UpdateArticleDTO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateByID", ctx, id, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateByID indicates an expected call of UpdateByID.
func (mr *MockArticleRepositoryMockRecorder) UpdateByID(ctx, id, dto interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateByID", reflect.TypeOf((*MockArticleRepository)(nil).UpdateByID), ctx, id, dto)
}
